const $=s=>document.querySelector(s);const startView=$('#startView'),editorView=$('#editorView'),previewView=$('#previewView');let photos=[];
const today=new Date();$('#reportDate').value=new Date(today.getTime()-today.getTimezoneOffset()*60000).toISOString().slice(0,10);
$('#startBtn').onclick=()=>showEditor();$('#newReportBtn').onclick=()=>{if(confirm('Start a new report? Current unsaved report data will be cleared.')){reset();showEditor()}};
function showEditor(){startView.hidden=true;previewView.hidden=true;editorView.hidden=false;scrollTo(0,0)}
function reset(){photos=[];$('#reportForm').reset();$('#reportDate').value=new Date(new Date().getTime()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);renderPhotos()}
$('#photoInput').addEventListener('change',async e=>{const files=[...e.target.files];if(!files.length)return;for(const file of files){if(!file.type.startsWith('image/'))continue;const url=await readURL(file);photos.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random()),url,file,note:''})}e.target.value='';renderPhotos();toast(`${files.length} photo${files.length===1?'':'s'} added`)});
function readURL(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
function renderPhotos(){const list=$('#photoList');list.innerHTML='';$('#photoCount').textContent=`${photos.length} photo${photos.length===1?'':'s'}`;photos.forEach((p,i)=>{const el=document.createElement('div');el.className='photoItem';el.draggable=true;el.dataset.id=p.id;el.innerHTML=`<img class="thumb" src="${p.url}" alt="Photo ${i+1}"><div class="photoMeta"><div class="photoNum">PHOTO ${i+1}</div><textarea placeholder="Add a note or caption...">${escapeHtml(p.note)}</textarea></div><button class="delete" type="button">Delete</button>`;el.querySelector('textarea').addEventListener('input',e=>p.note=e.target.value);el.querySelector('.delete').onclick=()=>{photos=photos.filter(x=>x.id!==p.id);renderPhotos()};el.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',p.id));el.addEventListener('dragover',e=>e.preventDefault());el.addEventListener('drop',e=>{e.preventDefault();const from=e.dataTransfer.getData('text/plain'),to=p.id;if(from===to)return;const a=photos.findIndex(x=>x.id===from),b=photos.findIndex(x=>x.id===to);const [m]=photos.splice(a,1);photos.splice(b,0,m);renderPhotos()});list.appendChild(el)})}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#previewBtn').onclick=()=>{if(!$('#projectName').value.trim()){toast('Please enter a project or job name.');$('#projectName').focus();return}renderPreview();editorView.hidden=true;previewView.hidden=false;scrollTo(0,0)};
$('#backBtn').onclick=()=>{previewView.hidden=true;editorView.hidden=false;scrollTo(0,0)};
function val(id){return escapeHtml($('#'+id).value.trim())}
function renderPreview(){const title=val('reportTitle')||'Field Report';const project=val('projectName');const client=val('clientName')||'Not provided';const date=val('reportDate')||'Not provided';const ref=val('reference')||'Not provided';const prepared=val('preparedBy')||'Not provided';const items=photos.map((p,i)=>`<article class="reportPhoto"><img src="${p.url}" alt="Photo ${i+1}"><div class="caption"><strong>Photo ${i+1}</strong>${p.note?`<br>${escapeHtml(p.note)}`:''}</div></article>`).join('');$('#reportPreview').innerHTML=`<div class="reportPage"><header class="reportHeader"><p class="eyebrow">NBRP FIELD REPORT</p><h1>${title}</h1><div class="meta"><div><strong>Project:</strong> ${project}</div><div><strong>Client:</strong> ${client}</div><div><strong>Date:</strong> ${date}</div><div><strong>Reference:</strong> ${ref}</div><div><strong>Prepared by:</strong> ${prepared}</div></div></header>${items||'<p class="muted">No photos have been added.</p>'}<div class="footer"><span>NBRP Field Report</span><span>Page 1</span></div></div>`}
$('#printBtn').onclick=()=>{renderPreview();setTimeout(()=>window.print(),80)};
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
renderPhotos();
