import indexHtml from './index.html'
import loginHtml from './login.html'
import registerHtml from './register.html'
import adminHtml from './admin.html'
import { Router } from 'itty-router'

const apiJs = `(function(){
  const base=(window.NBRP_CONFIG&&window.NBRP_CONFIG.API_BASE||'').replace(/\/$/,'');
  async function request(path, options={}){
    const res=await fetch(base+path,{credentials:'include',...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});
    let data=null; try{data=await res.json()}catch{}
    if(!res.ok) throw new Error((data&&data.error)||\`Request failed (\${res.status})\`);
    return data;
  }
  window.NBRPApi={
    me:()=>request('/api/me'),
    register:(body)=>request('/api/auth/register',{method:'POST',body:JSON.stringify(body)}),
    login:(body)=>request('/api/auth/login',{method:'POST',body:JSON.stringify(body)}),
    logout:()=>request('/api/auth/logout',{method:'POST'}),
    listReports:(q='')=>request('/api/reports'+(q?'?q='+encodeURIComponent(q):'')),
    getReport:(id)=>request('/api/reports/'+encodeURIComponent(id)),
    createReport:(body)=>request('/api/reports',{method:'POST',body:JSON.stringify(body)}),
    updateReport:(id,body)=>request('/api/reports/'+encodeURIComponent(id),{method:'PUT',body:JSON.stringify(body)}),
    deleteReport:(id)=>request('/api/reports/'+encodeURIComponent(id),{method:'DELETE'}),
    duplicateReport:(id)=>request('/api/reports/'+encodeURIComponent(id)+'/duplicate',{method:'POST'}),
    updatePhotoNote:(reportId,photoId,note)=>request('/api/reports/'+encodeURIComponent(reportId)+'/photos/'+encodeURIComponent(photoId),{method:'PUT',body:JSON.stringify({note})}),
    adminOverview:()=>request('/api/admin/overview'),
    adminUsers:(q='')=>request('/api/admin/users'+(q?'?q='+encodeURIComponent(q):'')),
    uploadPhoto:async(reportId,file,note='',sortOrder=0)=>{const fd=new FormData();fd.append('file',file);fd.append('note',note);fd.append('sort_order',String(sortOrder));const res=await fetch(base+'/api/reports/'+encodeURIComponent(reportId)+'/photos',{method:'POST',credentials:'include',body:fd});const data=await res.json();if(!res.ok)throw new Error(data.error||'Upload failed');return data;},
    deletePhoto:(reportId,photoId)=>request('/api/reports/'+encodeURIComponent(reportId)+'/photos/'+encodeURIComponent(photoId),{method:'DELETE'}),
    reorderPhotos:(reportId,ids)=>request('/api/reports/'+encodeURIComponent(reportId)+'/photos/reorder',{method:'POST',body:JSON.stringify({ids})}),
    uploadSignature:async(reportId,blob)=>{const fd=new FormData();fd.append('file',blob,'signature.png');const res=await fetch(base+'/api/reports/'+encodeURIComponent(reportId)+'/signature',{method:'POST',credentials:'include',body:fd});const data=await res.json();if(!res.ok)throw new Error(data.error||'Signature upload failed');return data;},
    mediaUrl:(key)=>key
  };
})();`
const configJs = `window.NBRP_CONFIG = { API_BASE: '' };`

const router=Router()
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}})
const now=()=>new Date().toISOString(), id=()=>crypto.randomUUID()
const bytes=n=>{const a=new Uint8Array(n);crypto.getRandomValues(a);return a}
const hex=a=>[...a].map(x=>x.toString(16).padStart(2,'0')).join('')
const sha256=async s=>hex(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))))
async function passwordHash(password,saltHex){const salt=Uint8Array.from((saltHex.match(/.{2}/g)||[]).map(x=>parseInt(x,16)));const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:150000,hash:'SHA-256'},key,256);return hex(new Uint8Array(bits))}
const cookieToken=req=>(req.headers.get('Cookie')||'').match(/nbrp_session=([^;]+)/)?.[1]||''
const requireMedia=env=>{if(!env.MEDIA)throw new Response(JSON.stringify({error:'Media storage is not configured yet'}),{status:503,headers:{'content-type':'application/json'}});return env.MEDIA}
async function auth(req,env){const raw=cookieToken(req);if(!raw)throw new Response(JSON.stringify({error:'Authentication required'}),{status:401,headers:{'content-type':'application/json'}});const row=await env.DB.prepare('SELECT s.user_id,s.expires_at,u.id,u.email,u.role,u.company,u.disabled,u.trial_ends_at,u.subscription_status FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?').bind(await sha256(raw),now()).first();if(!row||row.disabled)throw new Response(JSON.stringify({error:'Authentication required'}),{status:401,headers:{'content-type':'application/json'}});return row}
async function setSession(userId,env){const raw=hex(bytes(32)),expires=new Date(Date.now()+86400000*Number(env.SESSION_DAYS||14)).toISOString();await env.DB.prepare('INSERT INTO sessions(id,user_id,token_hash,expires_at,created_at) VALUES(?,?,?,?,?)').bind(id(),userId,await sha256(raw),expires,now()).run();return `nbrp_session=${raw}; Path=/; HttpOnly; Secure; SameSite=None; Max-Age=${86400*Number(env.SESSION_DAYS||14)}`}
const validatePassword=p=>typeof p==='string'&&p.length>=8&&p.length<=200
async function nextReportNumber(env){const day=now().slice(0,10),stamp=day.replaceAll('-','');await env.DB.prepare('INSERT OR IGNORE INTO daily_counters(day,value) VALUES(?,0)').bind(day).run();await env.DB.prepare('UPDATE daily_counters SET value=value+1 WHERE day=?').bind(day).run();const r=await env.DB.prepare('SELECT value FROM daily_counters WHERE day=?').bind(day).first();return `FR-${stamp}-${String(r.value).padStart(4,'0')}`}
async function getReport(env,userId,reportId){const r=await env.DB.prepare('SELECT * FROM reports WHERE id=? AND user_id=? AND deleted_at IS NULL').bind(reportId,userId).first();if(!r)return null;const ps=await env.DB.prepare('SELECT id,object_key,original_name,mime_type,size_bytes,sort_order,note,rotation,created_at FROM photos WHERE report_id=? ORDER BY sort_order,id').bind(reportId).all();return {...r,photos:ps.results.map(p=>({...p,url:`${env.APP_ORIGIN}/api/reports/${r.id}/photos/${p.id}/file`})),signature_r2_key:r.signature_key||null,signature_url:r.signature_key?`${env.APP_ORIGIN}/api/reports/${r.id}/signature/file`:null}}
function reportPayload(b){return {report_date:String(b.report_date||''),customer_name:String(b.customer_name||''),site_name:String(b.site_name||''),site_address:String(b.site_address||''),contact_name:String(b.contact_name||''),contact_phone:String(b.contact_phone||''),contact_email:String(b.contact_email||''),work_summary:String(b.work_summary||''),findings:String(b.findings||''),recommendations:String(b.recommendations||'')}}

router.post('/api/auth/register',async(req,env)=>{const b=await req.json(),email=String(b.email||'').trim().toLowerCase(),password=b.password;if(!/^\S+@\S+\.\S+$/.test(email)||!validatePassword(password))return json({error:'Use a valid email and a password of at least 8 characters'},400);if(await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first())return json({error:'An account with this email already exists'},409);const uid=id(),salt=hex(bytes(16)),hash=await passwordHash(password,salt),start=new Date(),end=new Date(start.getTime()+14*86400000),role=(env.OWNER_EMAIL||'').toLowerCase()===email?'owner':'customer';await env.DB.prepare('INSERT INTO users(id,email,password_hash,password_salt,role,created_at,trial_started_at,trial_ends_at) VALUES(?,?,?,?,?,?,?,?)').bind(uid,email,hash,salt,role,start.toISOString(),start.toISOString(),end.toISOString()).run();return json({ok:true,user:{id:uid,email,role}},201,{'set-cookie':await setSession(uid,env)})})
router.post('/api/auth/login',async(req,env)=>{const b=await req.json(),email=String(b.email||'').trim().toLowerCase(),u=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(email).first();if(!u||u.disabled)return json({error:'Invalid email or password'},401);if(await passwordHash(b.password||'',u.password_salt)!==u.password_hash)return json({error:'Invalid email or password'},401);return json({ok:true,user:{id:u.id,email:u.email,role:u.role,company:u.company,trialEndsAt:u.trial_ends_at,subscriptionStatus:u.subscription_status}},200,{'set-cookie':await setSession(u.id,env)})})
router.post('/api/auth/logout',async(req,env)=>{const raw=cookieToken(req);if(raw)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha256(raw)).run();return json({ok:true},200,{'set-cookie':'nbrp_session=; Path=/; HttpOnly; Secure; SameSite=None; Max-Age=0'})})
router.get('/api/me',async(req,env)=>{const u=await auth(req,env);return json({user:{id:u.id,email:u.email,role:u.role,company:u.company,trialEndsAt:u.trial_ends_at,subscriptionStatus:u.subscription_status}})})
router.get('/api/reports',async(req,env)=>{const u=await auth(req,env),url=new URL(req.url),q=url.searchParams.get('q')||'',status=url.searchParams.get('status')||'all',sort=url.searchParams.get('sort')||'updated';let sql='SELECT id,report_number,status,customer_name,site_name,report_date,updated_at FROM reports WHERE user_id=? AND deleted_at IS NULL',bind=[u.id];if(q){sql+=' AND (report_number LIKE ? OR customer_name LIKE ? OR site_name LIKE ? OR contact_name LIKE ?)';const x=`%${q}%`;bind.push(x,x,x,x)}if(status!=='all'){sql+=' AND status=?';bind.push(status)}sql+=' ORDER BY '+(sort==='date'?'report_date DESC':sort==='name'?'customer_name COLLATE NOCASE ASC':'updated_at DESC')+' LIMIT 200';return json({reports:(await env.DB.prepare(sql).bind(...bind).all()).results})})
router.get('/api/reports/:id',async(req,env)=>{const u=await auth(req,env),r=await getReport(env,u.id,req.params.id);return r?json({report:r}):json({error:'Report not found'},404)})
router.post('/api/reports',async(req,env)=>{const u=await auth(req,env),b=reportPayload(await req.json()),rid=id(),rn=await nextReportNumber(env),t=now();await env.DB.prepare('INSERT INTO reports(id,user_id,report_number,status,report_date,customer_name,site_name,site_address,contact_name,contact_phone,contact_email,work_summary,findings,recommendations,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(rid,u.id,rn,'draft',b.report_date||t.slice(0,10),b.customer_name,b.site_name,b.site_address,b.contact_name,b.contact_phone,b.contact_email,b.work_summary,b.findings,b.recommendations,t,t).run();return json({report:await getReport(env,u.id,rid)},201)})
router.put('/api/reports/:id',async(req,env)=>{const u=await auth(req,env),b=await req.json(),p=reportPayload(b),status=String(b.status||'draft'),t=now();const r=await env.DB.prepare('UPDATE reports SET status=?,report_date=?,customer_name=?,site_name=?,site_address=?,contact_name=?,contact_phone=?,contact_email=?,work_summary=?,findings=?,recommendations=?,updated_at=? WHERE id=? AND user_id=? AND deleted_at IS NULL').bind(status,p.report_date,p.customer_name,p.site_name,p.site_address,p.contact_name,p.contact_phone,p.contact_email,p.work_summary,p.findings,p.recommendations,t,req.params.id,u.id).run();if(!r.success)return json({error:'Report not found'},404);return json({report:await getReport(env,u.id,req.params.id)})})
router.delete('/api/reports/:id',async(req,env)=>{const u=await auth(req,env),r=await getReport(env,u.id,req.params.id);if(!r)return json({error:'Report not found'},404);if(env.MEDIA){for(const p of await env.DB.prepare('SELECT object_key FROM photos WHERE report_id=?').bind(req.params.id).all().then(x=>x.results))await env.MEDIA.delete(p.object_key);if(r.signature_key)await env.MEDIA.delete(r.signature_key)}await env.DB.prepare('UPDATE reports SET deleted_at=?,updated_at=? WHERE id=? AND user_id=?').bind(now(),now(),req.params.id,u.id).run();return json({ok:true})})
router.post('/api/reports/:id/duplicate',async(req,env)=>{const u=await auth(req,env),src=await getReport(env,u.id,req.params.id);if(!src)return json({error:'Report not found'},404);const rid=id(),rn=await nextReportNumber(env),t=now();await env.DB.prepare('INSERT INTO reports(id,user_id,report_number,status,report_date,customer_name,site_name,site_address,contact_name,contact_phone,contact_email,work_summary,findings,recommendations,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(rid,u.id,rn,'draft',src.report_date,src.customer_name,src.site_name,src.site_address,src.contact_name,src.contact_phone,src.contact_email,src.work_summary,src.findings,src.recommendations,t,t).run();if(env.MEDIA){for(const p of src.photos){const np=id(),key=`photos/${rid}/${np}`;const o=await env.MEDIA.get(`photos/${src.id}/${p.id}`);if(o)await env.MEDIA.put(key,o.body,{httpMetadata:o.httpMetadata});await env.DB.prepare('INSERT INTO photos(id,report_id,object_key,original_name,mime_type,size_bytes,sort_order,note,rotation,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(np,rid,key,p.original_name,p.mime_type,p.size_bytes,p.sort_order,p.note,p.rotation,t).run()}}return json({report:await getReport(env,u.id,rid)},201)})
router.post('/api/reports/:id/photos',async(req,env)=>{const media=requireMedia(env),u=await auth(req,env),fd=await req.formData(),file=fd.get('file');if(!(file instanceof File))return json({error:'Image file required'},400);if(!file.type.startsWith('image/'))return json({error:'Image file required'},400);if(file.size>8*1024*1024)return json({error:'Photo is too large'},413);const r=await env.DB.prepare('SELECT id FROM reports WHERE id=? AND user_id=? AND deleted_at IS NULL').bind(req.params.id,u.id).first();if(!r)return json({error:'Report not found'},404);const pid=id(),key=`photos/${r.id}/${pid}`,max=await env.DB.prepare('SELECT COALESCE(MAX(sort_order),-1) m FROM photos WHERE report_id=?').bind(r.id).first(),t=now();await media.put(key,file.stream(),{httpMetadata:{contentType:file.type}});await env.DB.prepare('INSERT INTO photos(id,report_id,object_key,original_name,mime_type,size_bytes,sort_order,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(pid,r.id,key,file.name,file.type,file.size,Number(max.m)+1,t).run();await env.DB.prepare('UPDATE reports SET updated_at=? WHERE id=?').bind(t,r.id).run();return json({photo:{id:pid,r2_key:key,url:`${env.APP_ORIGIN}/api/reports/${r.id}/photos/${pid}/file`,original_name:file.name,mime_type:file.type,size_bytes:file.size,sort_order:Number(max.m)+1,note:'',rotation:0}},201)})
router.delete('/api/reports/:reportId/photos/:photoId',async(req,env)=>{const u=await auth(req,env),p=await env.DB.prepare('SELECT p.* FROM photos p JOIN reports r ON r.id=p.report_id WHERE p.id=? AND p.report_id=? AND r.user_id=? AND r.deleted_at IS NULL').bind(req.params.photoId,req.params.reportId,u.id).first();if(!p)return json({error:'Photo not found'},404);if(env.MEDIA)await env.MEDIA.delete(p.object_key);await env.DB.prepare('DELETE FROM photos WHERE id=?').bind(p.id).run();return json({ok:true})})
router.put('/api/reports/:reportId/photos/:photoId',async(req,env)=>{const u=await auth(req,env),b=await req.json(),p=await env.DB.prepare('SELECT p.id FROM photos p JOIN reports r ON r.id=p.report_id WHERE p.id=? AND p.report_id=? AND r.user_id=?').bind(req.params.photoId,req.params.reportId,u.id).first();if(!p)return json({error:'Photo not found'},404);await env.DB.prepare('UPDATE photos SET note=COALESCE(?,note),rotation=COALESCE(?,rotation) WHERE id=?').bind(b.note??null,b.rotation??null,p.id).run();return json({ok:true})})
router.post('/api/reports/:id/photos/reorder',async(req,env)=>{const u=await auth(req,env),b=await req.json(),r=await env.DB.prepare('SELECT id FROM reports WHERE id=? AND user_id=? AND deleted_at IS NULL').bind(req.params.id,u.id).first();if(!r)return json({error:'Report not found'},404);for(const [i,pid] of (b.ids||[]).entries())await env.DB.prepare('UPDATE photos SET sort_order=? WHERE id=? AND report_id=?').bind(i,pid,r.id).run();return json({ok:true})})
router.post('/api/reports/:id/signature',async(req,env)=>{const media=requireMedia(env),u=await auth(req,env),fd=await req.formData(),file=fd.get('file');if(!(file instanceof File)||file.size>2*1024*1024)return json({error:'Valid signature file required'},400);const r=await env.DB.prepare('SELECT id,signature_key FROM reports WHERE id=? AND user_id=? AND deleted_at IS NULL').bind(req.params.id,u.id).first();if(!r)return json({error:'Report not found'},404);if(r.signature_key)await media.delete(r.signature_key);const key=`signatures/${r.id}/${id()}.png`;await media.put(key,file.stream(),{httpMetadata:{contentType:'image/png'}});await env.DB.prepare('UPDATE reports SET signature_key=?,updated_at=? WHERE id=?').bind(key,now(),r.id).run();return json({ok:true})})
router.get('/api/reports/:id/signature/file',async(req,env)=>{const media=requireMedia(env),u=await auth(req,env),r=await env.DB.prepare('SELECT signature_key FROM reports WHERE id=? AND user_id=? AND deleted_at IS NULL').bind(req.params.id,u.id).first();if(!r?.signature_key)return new Response('Not found',{status:404});const o=await media.get(r.signature_key);if(!o)return new Response('Not found',{status:404});return new Response(o.body,{headers:{'content-type':'image/png','cache-control':'private, max-age=3600'}})})
router.get('/api/reports/:id/photos/:photoId/file',async(req,env)=>{const media=requireMedia(env),u=await auth(req,env),p=await env.DB.prepare('SELECT p.* FROM photos p JOIN reports r ON r.id=p.report_id WHERE p.id=? AND p.report_id=? AND r.user_id=? AND r.deleted_at IS NULL').bind(req.params.photoId,req.params.id,u.id).first();if(!p)return new Response('Not found',{status:404});const o=await media.get(p.object_key);if(!o)return new Response('Not found',{status:404});return new Response(o.body,{headers:{'content-type':p.mime_type||'image/jpeg','cache-control':'private, max-age=3600'}})})
router.get('/api/admin/overview',async(req,env)=>{const u=await auth(req,env);if(!['owner','admin'].includes(u.role))return json({error:'Forbidden'},403);const r=await env.DB.batch([env.DB.prepare('SELECT COUNT(*) c FROM users WHERE disabled=0'),env.DB.prepare("SELECT COUNT(*) c FROM users WHERE disabled=0 AND trial_ends_at>? AND subscription_status='none'").bind(now()),env.DB.prepare("SELECT COUNT(*) c FROM users WHERE disabled=0 AND subscription_status='active'"),env.DB.prepare('SELECT COUNT(*) c FROM reports WHERE deleted_at IS NULL'),env.DB.prepare("SELECT COUNT(*) c FROM reports WHERE deleted_at IS NULL AND status='draft'")]);return json({users:r[0].results[0].c,activeTrials:r[1].results[0].c,paid:r[2].results[0].c,reports:r[3].results[0].c,drafts:r[4].results[0].c,completed:0})})
router.get('/api/admin/users',async(req,env)=>{const u=await auth(req,env);if(!['owner','admin'].includes(u.role))return json({error:'Forbidden'},403);const q=new URL(req.url).searchParams.get('q')||'';let sql='SELECT id,email,role,company,created_at,trial_ends_at,subscription_status,disabled FROM users',bind=[];if(q){sql+=' WHERE email LIKE ? OR company LIKE ?';const x=`%${q}%`;bind=[x,x]}sql+=' ORDER BY created_at DESC LIMIT 500';return json({users:(await env.DB.prepare(sql).bind(...bind).all()).results})})
router.all('*',()=>json({error:'Not found'},404))

export default {async fetch(request,env){
  const origin=request.headers.get('Origin');const allow=env.APP_ORIGIN||origin||'*';
  if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':allow,'Access-Control-Allow-Credentials':'true','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,PUT,PATCH,DELETE,OPTIONS'}});
  try{const pathname=new URL(request.url).pathname;const pages={'/':indexHtml,'/index.html':indexHtml,'/login.html':loginHtml,'/register.html':registerHtml,'/admin.html':adminHtml,'/api.js':apiJs,'/config.js':configJs};const isApi=pathname.startsWith('/api/');if(!isApi&&!pages[pathname])return json({error:'Not found'},404);const r=isApi?await router.fetch(request,env):new Response(pages[pathname],{status:200,headers:{'content-type':pathname.endsWith('.js')?'application/javascript; charset=utf-8':'text/html; charset=utf-8','cache-control':'no-store'}}),h=new Headers(r.headers);if(origin&&(!env.APP_ORIGIN||origin===env.APP_ORIGIN)){h.set('Access-Control-Allow-Origin',origin);h.set('Access-Control-Allow-Credentials','true')}return new Response(r.body,{status:r.status,headers:h})}catch(e){if(e instanceof Response)return e;return json({error:'Server error'},500)}}}
