const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Access-Control-Allow-Credentials':'true',...extra}});
const cors=(origin)=>({'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS','Access-Control-Allow-Headers':'Content-Type','Vary':'Origin'});
const now=()=>new Date().toISOString();
const uid=()=>crypto.randomUUID();
function cookie(name,value,maxAge){return `${name}=${value}; Path=/; HttpOnly; Secure; SameSite=None; Max-Age=${maxAge}`}
async function hashPassword(password){const enc=new TextEncoder();const salt=crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:120000,hash:'SHA-256'},key,256);return btoa(String.fromCharCode(...salt))+'.'+btoa(String.fromCharCode(...new Uint8Array(bits)))}
async function verifyPassword(password,stored){const [a,b]=stored.split('.');const salt=Uint8Array.from(atob(a),c=>c.charCodeAt(0));const expected=Uint8Array.from(atob(b),c=>c.charCodeAt(0));const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:120000,hash:'SHA-256'},key,256));let diff=bits.length^expected.length;for(let i=0;i<bits.length;i++)diff|=bits[i]^expected[i];return diff===0}
function getCookie(req,name){const c=req.headers.get('Cookie')||'';const m=c.match(new RegExp('(?:^|; )'+name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'=([^;]*)'));return m?m[1]:null}
async function auth(req,env){const sid=getCookie(req,'nbrp_session');if(!sid)return null;const row=await env.DB.prepare('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at>?').bind(sid,now()).first();return row||null}
function safeUser(u){return {id:u.id,email:u.email,name:u.name,company:u.company,role:u.role,trial_started_at:u.trial_started_at,trial_ends_at:u.trial_ends_at,created_at:u.created_at}}
function nextReportNumber(){return null}
async function allocateReportNumber(env){const day=new Date().toISOString().slice(0,10).replace(/-/g,'');for(let i=1;i<100000;i++){const n=`FR-${day}-${String(i).padStart(4,'0')}`;const exists=await env.DB.prepare('SELECT id FROM reports WHERE report_number=?').bind(n).first();if(!exists)return n}throw new Error('Report number allocation exhausted')}
async function audit(env,userId,action,targetType='',targetId='',metadata=''){await env.DB.prepare('INSERT INTO audit_logs(id,user_id,action,target_type,target_id,metadata,created_at) VALUES(?,?,?,?,?,?,?)').bind(uid(),userId,action,targetType,targetId,metadata,now()).run()}
async function parseJson(req){try{return await req.json()}catch{return {}}}
export default {async fetch(req,env){const origin=env.APP_ORIGIN||'*';if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(origin)});const url=new URL(req.url);const headers=cors(origin);try{
if(url.pathname==='/api/health')return json({ok:true,service:'nbrp-fieldreport-api',time:now()},200,headers);
if(url.pathname==='/api/auth/register'&&req.method==='POST'){const b=await parseJson(req);const email=String(b.email||'').trim().toLowerCase();const password=String(b.password||'');const name=String(b.name||'').trim();const company=String(b.company||'').trim();if(!/^\S+@\S+\.\S+$/.test(email))return json({error:'Enter a valid email'},400,headers);if(password.length<8)return json({error:'Password must be at least 8 characters'},400,headers);if(name.length<2)return json({error:'Enter your name'},400,headers);const existing=await env.DB.prepare('SELECT id FROM users WHERE email=?').bind(email).first();if(existing)return json({error:'An account with this email already exists'},409,headers);const id=uid(),t=Date.now(),start=new Date(t),end=new Date(t+14*86400000);const ph=await hashPassword(password);await env.DB.prepare('INSERT INTO users(id,email,password_hash,name,company,role,trial_started_at,trial_ends_at,trial_used,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(id,email,ph,name,company,'customer',start.toISOString(),end.toISOString(),1,start.toISOString(),start.toISOString()).run();const sid=uid();await env.DB.prepare('INSERT INTO sessions(id,user_id,expires_at,created_at) VALUES(?,?,?,?)').bind(sid,id,new Date(t+14*86400000).toISOString(),start.toISOString()).run();await audit(env,id,'register','user',id);return json({user:safeUser({id,email,name,company,role:'customer',trial_started_at:start.toISOString(),trial_ends_at:end.toISOString(),created_at:start.toISOString()})},201,{...headers,'Set-Cookie':cookie('nbrp_session',sid,14*86400)})}
if(url.pathname==='/api/auth/login'&&req.method==='POST'){const b=await parseJson(req);const email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');const u=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind(email).first();if(!u||!(await verifyPassword(password,u.password_hash)))return json({error:'Invalid email or password'},401,headers);const sid=uid();await env.DB.prepare('INSERT INTO sessions(id,user_id,expires_at,created_at) VALUES(?,?,?,?)').bind(sid,u.id,new Date(Date.now()+14*86400000).toISOString(),now()).run();await audit(env,u.id,'login','user',u.id);return json({user:safeUser(u)},200,{...headers,'Set-Cookie':cookie('nbrp_session',sid,14*86400)})}
if(url.pathname==='/api/auth/logout'&&req.method==='POST'){const sid=getCookie(req,'nbrp_session');if(sid)await env.DB.prepare('DELETE FROM sessions WHERE id=?').bind(sid).run();return json({ok:true},200,{...headers,'Set-Cookie':cookie('nbrp_session','',0)})}
if(url.pathname==='/api/me'&&req.method==='GET'){const u=await auth(req,env);if(!u)return json({error:'Not authenticated'},401,headers);return json({user:safeUser(u)},200,headers)}
const u=await auth(req,env);if(!u)return json({error:'Authentication required'},401,headers);
if(url.pathname.startsWith('/api/media/')&&req.method==='GET'){const key=decodeURIComponent(url.pathname.slice('/api/media/'.length));if(!key.startsWith('users/'+u.id+'/'))return json({error:'Access denied'},403,headers);const obj=await env.MEDIA.get(key);if(!obj)return new Response('Not found',{status:404,headers});return new Response(obj.body,{status:200,headers:{...headers,'Content-Type':obj.httpMetadata?.contentType||'application/octet-stream','Cache-Control':'private, max-age=3600'}})}
if(url.pathname==='/api/admin/overview'&&req.method==='GET'){if(!['admin','owner'].includes(u.role))return json({error:'Access denied'},403,headers);const [users,reports,drafts,completed,trials]=await Promise.all([env.DB.prepare('SELECT COUNT(*) c FROM users').first(),env.DB.prepare('SELECT COUNT(*) c FROM reports').first(),env.DB.prepare("SELECT COUNT(*) c FROM reports WHERE status='draft'").first(),env.DB.prepare("SELECT COUNT(*) c FROM reports WHERE status='completed'").first(),env.DB.prepare("SELECT COUNT(*) c FROM users WHERE trial_ends_at>? AND trial_used=1").bind(now()).first()]);return json({users:Number(users.c),reports:Number(reports.c),drafts:Number(drafts.c),completed:Number(completed.c),activeTrials:Number(trials.c)},200,headers)}
if(url.pathname==='/api/admin/users'&&req.method==='GET'){if(!['admin','owner'].includes(u.role))return json({error:'Access denied'},403,headers);const q=(url.searchParams.get('q')||'').trim();let sql='SELECT id,email,name,company,role,trial_started_at,trial_ends_at,trial_used,created_at FROM users';const args=[];if(q){sql+=' WHERE email LIKE ? OR name LIKE ? OR company LIKE ?';args.push('%'+q+'%','%'+q+'%','%'+q+'%')}sql+=' ORDER BY created_at DESC LIMIT 100';const r=await env.DB.prepare(sql).bind(...args).all();return json({users:r.results},200,headers)}
if(url.pathname==='/api/reports'&&req.method==='GET'){const q=(url.searchParams.get('q')||'').trim();let sql='SELECT id,report_number,status,report_date,customer_name,site_name,updated_at,created_at FROM reports WHERE user_id=?';const args=[u.id];if(q){sql+=' AND (report_number LIKE ? OR customer_name LIKE ? OR site_name LIKE ?)';args.push('%'+q+'%','%'+q+'%','%'+q+'%')}sql+=' ORDER BY updated_at DESC';const r=await env.DB.prepare(sql).bind(...args).all();return json({reports:r.results},200,headers)}
if(url.pathname==='/api/reports'&&req.method==='POST'){const b=await parseJson(req);const id=uid(),n=await allocateReportNumber(env),t=now();await env.DB.prepare('INSERT INTO reports(id,report_number,user_id,status,report_date,customer_name,site_name,site_address,contact_name,contact_phone,contact_email,work_summary,findings,recommendations,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,n,u.id,b.status==='completed'?'completed':'draft',String(b.report_date||t.slice(0,10)),String(b.customer_name||''),String(b.site_name||''),String(b.site_address||''),String(b.contact_name||''),String(b.contact_phone||''),String(b.contact_email||''),String(b.work_summary||''),String(b.findings||''),String(b.recommendations||''),t,t).run();await audit(env,u.id,'create_report','report',id);return json({report:await env.DB.prepare('SELECT * FROM reports WHERE id=?').bind(id).first()},201,headers)}
const m=url.pathname.match(/^\/api\/reports\/([^/]+)(?:\/([^/]+))?(?:\/([^/]+))?$/);if(m){const id=decodeURIComponent(m[1]),sub=m[2],sub2=m[3];const report=await env.DB.prepare('SELECT * FROM reports WHERE id=? AND user_id=?').bind(id,u.id).first();if(!report)return json({error:'Report not found'},404,headers);
if(!sub&&req.method==='GET'){const photos=await env.DB.prepare('SELECT * FROM report_photos WHERE report_id=? ORDER BY sort_order ASC').bind(id).all();return json({report,photos:photos.results},200,headers)}
if(!sub&&req.method==='PUT'){const b=await parseJson(req);await env.DB.prepare('UPDATE reports SET status=?,report_date=?,customer_name=?,site_name=?,site_address=?,contact_name=?,contact_phone=?,contact_email=?,work_summary=?,findings=?,recommendations=?,updated_at=? WHERE id=?').bind(b.status==='completed'?'completed':'draft',String(b.report_date||report.report_date),String(b.customer_name||''),String(b.site_name||''),String(b.site_address||''),String(b.contact_name||''),String(b.contact_phone||''),String(b.contact_email||''),String(b.work_summary||''),String(b.findings||''),String(b.recommendations||''),now(),id).run();return json({report:await env.DB.prepare('SELECT * FROM reports WHERE id=?').bind(id).first()},200,headers)}
if(!sub&&req.method==='POST'&&url.searchParams.get('action')==='duplicate'){const nid=uid(),nn=await allocateReportNumber(env),t=now();await env.DB.prepare('INSERT INTO reports(id,report_number,user_id,status,report_date,customer_name,site_name,site_address,contact_name,contact_phone,contact_email,work_summary,findings,recommendations,signature_r2_key,created_at,updated_at) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,? FROM reports WHERE id=?').bind(nid,nn,u.id,'draft',report.report_date,report.customer_name,report.site_name,report.site_address,report.contact_name,report.contact_phone,report.contact_email,report.work_summary,report.findings,report.recommendations,'',t,t,id).run();return json({report:await env.DB.prepare('SELECT * FROM reports WHERE id=?').bind(nid).first()},201,headers)}
if(!sub&&req.method==='DELETE'){await env.DB.prepare('DELETE FROM reports WHERE id=?').bind(id).run();await audit(env,u.id,'delete_report','report',id);return json({ok:true},200,headers)}
if(sub==='photos'&&sub2==='reorder'&&req.method==='POST'){const b=await parseJson(req);const ids=Array.isArray(b.ids)?b.ids:[];for(let i=0;i<ids.length;i++)await env.DB.prepare('UPDATE report_photos SET sort_order=? WHERE id=? AND report_id=?').bind(i,ids[i],id).run();await env.DB.prepare('UPDATE reports SET updated_at=? WHERE id=?').bind(now(),id).run();return json({ok:true},200,headers)}
if(sub==='photos'&&sub2&&req.method==='PUT'){const b=await parseJson(req);await env.DB.prepare('UPDATE report_photos SET note=? WHERE id=? AND report_id=?').bind(String(b.note||''),decodeURIComponent(sub2),id).run();return json({ok:true},200,headers)}
if(sub==='photos'&&sub2&&req.method==='DELETE'){const p=await env.DB.prepare('SELECT * FROM report_photos WHERE id=? AND report_id=?').bind(decodeURIComponent(sub2),id).first();if(!p)return json({error:'Photo not found'},404,headers);await env.MEDIA.delete(p.r2_key);await env.DB.prepare('DELETE FROM report_photos WHERE id=?').bind(p.id).run();return json({ok:true},200,headers)}
}
if(m&&m[2]==='photos'&&req.method==='POST'){
 const fd=await req.formData(),file=fd.get('file');if(!(file instanceof File))return json({error:'Photo file is required'},400,headers);if(file.size>15*1024*1024)return json({error:'Photo is too large'},413,headers);if(!file.type.startsWith('image/'))return json({error:'Only image files are allowed'},400,headers);const id=uid(),key=`users/${u.id}/reports/${m[1]}/photos/${id}`;await env.MEDIA.put(key,file.stream(),{httpMetadata:{contentType:file.type}});const max=(await env.DB.prepare('SELECT COALESCE(MAX(sort_order),-1) m FROM report_photos WHERE report_id=?').bind(m[1]).first()).m;await env.DB.prepare('INSERT INTO report_photos(id,report_id,r2_key,original_name,note,sort_order,created_at) VALUES(?,?,?,?,?,?,?)').bind(id,m[1],key,file.name||'',String(fd.get('note')||''),Number(fd.get('sort_order')??(max+1)),now()).run();return json({photo:{id,r2_key:key,original_name:file.name||'',note:String(fd.get('note')||'')}},201,headers)}
if(m&&m[2]==='signature'&&req.method==='POST'){const fd=await req.formData(),file=fd.get('file');if(!(file instanceof File))return json({error:'Signature file is required'},400,headers);const key=`users/${u.id}/reports/${m[1]}/signature.png`;await env.MEDIA.put(key,file.stream(),{httpMetadata:{contentType:file.type||'image/png'}});await env.DB.prepare('UPDATE reports SET signature_r2_key=?,updated_at=? WHERE id=?').bind(key,now(),m[1]).run();return json({ok:true,key},200,headers)}
return json({error:'Not found'},404,headers);
}catch(e){return json({error:e.message||'Server error'},500,headers)}}}
